ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM registry.cn-shenzhen.aliyuncs.com/tuhms_elk/kibana-oss:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
