ARG ELK_VERSION=6.4.0

# https://github.com/elastic/elasticsearch-docker
FROM registry.cn-shenzhen.aliyuncs.com/tuhms_elk/elasticsearch-oss:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
