ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
FROM registry.cn-shenzhen.aliyuncs.com/tuhms_elk/logstash-oss:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
